name: flutter_blog_preview_card
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^1.0.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-VariableFont_wght.ttf
        - asset: assets/fonts/static/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Figtree-ExtraBold.ttf
          weight: 800
